### ISSUE TITLE
Minkowski distance implementation

### ISSUE THREAD

**Issue by ghost** [dainiusjocas/Data-Mining#4]
Minkowski distance should be implemented, so we could evaluate and compare the algorithms more precisely. By default the Manhattan distance should be used (p=1), but also a user should be able to choose euclidian distance (p=2) or any other value of parameter p.

**Comment by dainiusjocas** [comment]
Now it is possible to compute distance of numeric values of level that you want. You can pass four parameters to function get_distance_between_numeric_values, where fourth parameter is optional and it's default value is 1. So, if pass only three parameters to function manhattan distance. If your fourth parameter was 2 than function would compute euclidean distance and so on.
